name: 🔨 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:           

jobs:
  build_and_test:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'  
          # cache: 'pnpm'       

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile 

      - name: Build Extension (Chromium Production)
        run: pnpm build  
      
      - name: Build Extension (Firefox Production)
        run: pnpm build:firefox

      # - name: Run Tests
        # run: pnpm test
